# Generated by Django 4.2 on 2023-04-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employers.companyprofile",
            ),
        ),
    ]
