# Generated by Django 4.2 on 2023-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_alter_applicantprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
    ]
