# Generated by Django 4.2 on 2023-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_jobapplication_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="is_applied",
            field=models.BooleanField(default=True),
        ),
    ]
